CREATE DATABASE IF NOT EXISTS College;
USE College
CREATE TABLE IF NOT EXISTS Student(Name VARCHAR(20), Roll_Number INTEGER);
DESC Student;
SELECT * FROM Student;
DROP TABLE IF EXISTS Student;
DROP DATABASE IF EXISTS College;